### ISSUE TITLE
怎么直接选择 年月日这种形式  而不是使用英语的方式呢

### ISSUE THREAD

**Issue by chenqiang1121** [rnkit/rnkit-actionsheet-picker#11]
我这是想做一个生日选择器，想按照年 月  日  这种方式  按照传统的中文方式进行选择，但是没有找到方法

**Comment by simman** [comment]
是选择时候的格式还是获取之后的格式？

**Comment by simman** [comment]
不就是这种的吗？
<img width="573" alt="qq20170523-192206 2x" src="https://cloud.githubusercontent.com/assets/2041471/26352176/34623e92-3fed-11e7-92cc-6bf99ea43e02.png">

**Comment by chenqiang1121** [comment]
是我的模拟器没有选择语言，多谢了啊
