### ISSUE TITLE
是否有 从多少到多少的效果

### ISSUE THREAD

**Issue by 7caishi** [rnkit/rnkit-actionsheet-picker#17]
比如  18岁-23岁
左右分别有两个picker 并且不需要联动

**Comment by simman** [comment]
暂时不行, 欢迎 pr ！

**Comment by 7caishi** [comment]
自定义也没办法解决吗？或者你知道有没有类似效果兼容安卓和IOS的

**Comment by simman** [comment]
只能改源码实现，可以看下[https://github.com/rnkit/rnkit-actionsheet-picker/blob/master/ios/RNKitASDataPicker.m#L168](https://github.com/rnkit/rnkit-actionsheet-picker/blob/master/ios/RNKitASDataPicker.m#L168)

**Comment by 7caishi** [comment]
好的多谢,

**Comment by 7caishi** [comment]
@simman 是否能加你一下QQ 有点问题请教 54152649
