### ISSUE TITLE
cancelled when DatePicker.show is triggered

### ISSUE THREAD

**Issue by damathryx** [rnkit/rnkit-actionsheet-picker#4]
date picker cancelled when show is triggered for datepicker.

```
DatePicker.show({
      datePickerMode: 'date',
      onPickerConfirm: (selectedDate) => {
        console.log(selectedDate);
        this.setState({
          date: selectedDate
        })
      },
      onPickerCancel: () => {
        console.log('date picker canceled');
      },
      onPickerDidSelect: (selectedDate) => {
         console.log(selectedDate);
      }
})
```

Android
version. 0.0.8

**Comment by damathryx** [comment]
I was actually missing build tools 25.0.1. its fine now after installing and running 

> react-native run-android

**Comment by traf** [comment]
This actually still happens on the iOS version. I think this should be re-opened as an issue

**Comment by jariwalabhavesh** [comment]
@traf @damathryx
I think yes, ios having still same issue when opening date picker it is triggering cancel event each time we open datepicker.
