### ISSUE TITLE
change chinese text to english

### ISSUE THREAD

**Issue by damathryx** [rnkit/rnkit-actionsheet-picker#5]
I tried changing the values in strings.xml but still not taking effect? what am I missing

**Comment by simman** [comment]
see [https://github.com/rnkit/rnkit-actionsheet-picker#params](https://github.com/rnkit/rnkit-actionsheet-picker#params) !

#### Params
| Key | Type | Default | Description |
| --- | --- | --- | --- |
| titleText | string | '选择时间' | |
| titleTextColor | string | '#393939' |  |
| doneText | string | '确定' | |
| doneTextColor | string | '#269ff7' |  |
| cancelText | string | '选择时间' | |
| cancelTextColor | string | '#269ff7' |  |

**Comment by damathryx** [comment]
@simman 
I mean the text in datepicker 
![screen shot 2016-12-27 at 6 34 17 pm](https://cloud.githubusercontent.com/assets/14576761/21497917/2c415d9a-cc63-11e6-87c0-2206a128a66d.png)

**Comment by damathryx** [comment]
@simman 
![screen shot 2016-12-27 at 6 35 54 pm](https://cloud.githubusercontent.com/assets/14576761/21497959/799b3642-cc63-11e6-91f9-e256a6ea89d2.png)
